# Session times use the HH:MM:SS format. End times are exclusive.
[session]
active = rth

[rth]
start = 15:30:00
end = 23:00:00

[overnight]
start = 23:00:00
end = 15:30:00

[eth]
start = 01:00:00
end = 23:00:00